### ISSUE TITLE
VirtIO driver installation is broken

### ISSUE THREAD

**Issue by mikhirev** [grnet/snf-image-creator#44] opened 2015-02-20 18:31 UTC
Hi!
I tried to create Windows 7 image with snf-image creator 0.8.1, but I was unable to install VirtIO drivers. After entering directory name i got message "invalid dirname". It seems that _check_dir() received a list instead string as argument.
I also tried version 0.7.4. It allows to install drivers, but after installation driver list inverts: newly installed drivers are shown properly but the ones installed before are shown as missing. After one more attempt it inverts again and returns to original state.

**Comment by skalkoto** [comment] 2015-02-20 20:29
Hello,

Can you please resend this in an e-mail to synnefo@googlegroups.com? Also, include how you installed the software, the distro you are on and the exact command you used.

Nikos

**Comment by mikhirev** [comment] 2015-02-20 21:08
OK, I will do it on Tuesday, when I will be able to achieve that machine and reproduce the bug to describe it more precisely.
The system I used is Debian Wheezy, software was installed from repository
    deb http://apt.dev.grnet.gr wheezy

**Comment by skalkoto** [comment] 2015-02-24 13:03
Hello,

The "invalid dirname" error is indeed reproducable in 0.8.1. I checked the latest source and it seems to work alright. We have uploaded a 0.9rc1 version for wheezy today that seems to overcome this.

The second thing you mention if I understand it correct is that when you install virtIO drivers to a Windows media you would expect it to leave the old drivers in the drivers database and just install the new ones. Instead of this, snf-image-creator will do an upgrade (install the new drivers and completely remove the old ones). Well this is done in purpose.

For a reason I cannot understand, I've seen Windows VM's picking the old drivers after sysprep when both drivers are present. This can be catastrophic in some cases. For example, after upgrading QEMU, I've seen the older drivers causing a BSoF and having both drivers installed was not an option since the old ones where picked. Maybe we could separate those 2 processes and add 2 different options: --install-virtio and --upgrade-virtio, but do you actually need it? Is there any practical reason you want this?

I'm closing the issue for now. Please use the mailing list (synnefo@googlegroups.com) and I will reopen it if the problem persists.

**Comment by mikhirev** [comment] 2015-02-24 13:49
> The second thing you mention if I understand it correct is that when
> you install virtIO drivers to a Windows media you would expect it to
> leave the old drivers in the drivers database and just install the
> new ones. Instead of this, snf-image-creator will do an upgrade
> (install the new drivers and completely remove the old ones). Well
> this is done in purpose.
> 
> For a reason I cannot understand, I've seen Windows VM's picking the
> old drivers after sysprep when both drivers are present. This can be
> catastrophic in some cases. For example, after upgrading QEMU, I've
> seen the older drivers causing a BSoF and having both drivers
> installed was not an option since the old ones where picked. Maybe we
> could separate those 2 processes and add 2 different options:
> --install-virtio and --upgrade-virtio, but do you actually need it?
> Is there any practical reason you want this?
> 
Well, in my case I had viostor driver installed (at system installation
time) and all other drivers missing.  I specified path to directory
containing all drivers including viostor of *the same version* that was
installed earlier. I expected that after "update" I will have all
drivers installed, but in fact viostor was removed. As result, I was
unable to proceed with Sysprep, that requires all of viostor, netvm and
balloon drivers installed, and I could not find any way to resolve this
issue without installing drivers manually, because installing one
driver via snf-image-creator implied removal of other.

I don't think that one more option is necessary, but the existing one
should be fixed to work in such cases as I described.

-- 
Regards,
       Dmitry Mikhirev

**Comment by skalkoto** [comment] 2015-02-24 14:00
OK, now I get it! Well, this is probably a bug. I'll try to fix it for 0.9rc2.

**Closed** 2015-03-03 09:36 UTC
